name: AWS Env for Agworld
description: Evaluates an AWS Env and sets up the AWS_... variables accordingly
author: https://github.com/agworld
requirements:
- jq
configuration:
  properties: {}
  additionalProperties: false