#!/usr/bin/env bash
set -e
set -o pipefail
set -u

main() {
  local exports
  exports=$(cat "/root/.aws/cli/cache/$(ls -tr /root/.aws/cli/cache | tail -1)" | jq -r '.Credentials | "export AWS_ACCESS_KEY_ID=\"\(.AccessKeyId)\"\nexport AWS_SECRET_ACCESS_KEY=\"\(.SecretAccessKey)\"\n export AWS_SESSION_TOKEN=\"\(.SessionToken)\" "')

  eval "$exports"

  echo "Exported session credentials:"
  echo "  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
  echo "  AWS_SECRET_ACCESS_KEY=(${#AWS_SECRET_ACCESS_KEY} chars)"
  echo "  AWS_SESSION_TOKEN=(${#AWS_SESSION_TOKEN} chars)"
}

main